START TRANSACTION;
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'BAGERHAT', 'Bagerhat');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'বাগেরহাট');
INSERT IGNORE INTO directory_country_region(country_id, code, default_name) VALUES('BD', 'BANDARBAN', 'Bandarban');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'বান্দরবান');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'BARGUNA', 'Barguna');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'বরগুনা');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'BARISAL', 'Barisal');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'বরিশাল');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'BRAHMANBARIA', 'Brahmanbaria');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'ব্রাহ্মণবাড়ীয়া');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'BOGRA', 'Bogra');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'বগুড়া');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'BHOLA', 'Bhola');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'ভোলা');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'CHANDPUR', 'Chandpur');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'চাঁদপুর');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'CHITTAGONG', 'Chittagong');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'চট্টগ্রাম');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'CHUADANG', 'Chuadang');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'চুয়াডাঙ্গা');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'COMILLA', 'Comilla');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'কুমিল্লা');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'COXS BAZAR', "Cox's Bazar");
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'কক্সবাজার');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'DHAKA', 'Dhaka');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'ঢাকা');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'DINAJPUR', 'Dinajpur');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'দিনাজপুর');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'FARIDPUR', 'Faridpur');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'ফরিদপুর');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'FENI', 'Feni');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'ফেনী');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'GAIBANDHA', 'Gaibandha');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'গাইবান্ধা');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'GAZIPUR', 'Gazipur');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'গাজীপুর');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'GOPALGANJ', 'Gopalganj');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'গোপালগঞ্জ');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'HABIGANJ', 'Habiganj');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'হবিগঞ্জ');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'JOYPURHAT', 'Joypurhat');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'জয়পুরহাট');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'JAMALPUR', 'Jamalpur');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'জামালপুর');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'JESSORE', 'Jessore');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'যশোর');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'JHALOKATI', 'Jhalokati');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'ঝালকাঠি');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'JHENAIDAH', 'Jhenaidah');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'ঝিনাইদহ');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'KHAGRACHHARI', 'Khagracchari');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'খাগড়াছড়ি');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'KHULNA', 'Khulna');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'খুলনা');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'KISHORGANJ', 'Kishorganj');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'কিশোরগঞ্জ');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'KURIGRAM', 'Kurigram');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'কুড়িগ্রাম');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'KUSTIA', 'Kustia');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'কুষ্টিয়া');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'LAKSHMIPUR', 'Lakshmipur');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'লক্ষীপুর');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'LALMONIRHAT', 'Lalmonirhat');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'লালমনিরহাট');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'MADARIPUR', 'Madaripur');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'মাদারীপুর');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'MAGURA', 'Magura');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'মাগুরা');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'MANIKGANJ', 'Manikganj');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'মানিকগঞ্জ');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'MEHERPUR', 'Meherpur');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'মেহেরপুর');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'MOULVIBAZAR', 'Moulvibazar');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'মৌলভীবাজার');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'MUNSHIGANJ', 'Munshiganj');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'মুন্সীগঞ্জ');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'MYMENSINGH', 'Mymenshingh');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'ময়মনসিংহ');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'NAOGAON', 'Naogaon');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'নওগাঁ');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'NARAYANGANJ', 'Narayanganj');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'নারায়ণগঞ্জ');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'NARSHINGDI', 'Narshingdi');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'নরসিংদী');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'NATOR', 'Nator');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'নাটোর');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'NAWABGANJ', 'Nawabganj');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'নওয়াবগঞ্জ');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'NETROKONA', 'Netrokona');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'নেত্রকোনা');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'NILPHAMARI', 'Nilphamari');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'নীলফামারী');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'NOAKHALI', 'Noakhali');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'নোয়াখালী');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'NARAIL', 'Narail');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'নড়াইল');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'PABNA', 'Pabna');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'পাবনা');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'PANCHAGARH', 'Panchagarh');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'পঞ্চগড়');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'PATUAKHALI', 'Patuakhali');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'পটুয়াখালী');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'PIROJPUR', 'Pirojpur');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'পিরোজপুর');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'RAJBARi', 'Rajbari');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'রাজবাড়ী');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'RANGAMATI', 'Rangamati');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'রাঙ্গামাটি');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'RANGPUR', 'Rangpur');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'রংপুর');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'SATKHIRA', 'Shatkhira');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'সাতক্ষিরা');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'SHARIATPUR', 'Shariatpur');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'শরীয়তপুর');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'SHERPUR', 'Sherpur');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'শেরপুর');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'SIRAJGANJ', 'Sirajganj');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'সিরাজগঞ্জ');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'SUNAMGANJ', 'Sunamganj');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'সুনামগঞ্জ');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'SYLHET', 'Sylhet');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'সিলেট');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'TANGAIL', 'Tangail');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'টাঙ্গাইল');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'TAKURGAON', 'Takurgaon');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'ঠাকুরগাঁ');
INSERT IGNORE INTO directory_country_region (country_id, code, default_name) VALUES('BD', 'RAJSHAHI', 'Rajshahi');
INSERT IGNORE INTO directory_country_region_name (`locale`, `region_id`, `name`) VALUES	('bn_BD', LAST_INSERT_ID(), 'রাজশাহী');	
COMMIT;
